sudo: false

language: python
os:
  - linux
env:
  - aaa: bbb
python:
  - 2.7
  - pypy
  - 3.4
  - 3.5
  - 3.6

script:
  - pwd
  - ls /home/travis/build/lafite1759/reeduszhang
  - cd /home/travis/build/lafite1759/reeduszhang;chmod 755 *;./test.sh
